name: async-await npm package

on:
  push:
    tags:
      - "async-await*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
        working-directory: async-await

      - run: bun test
        working-directory: strings

      - run: bun run prepare
        working-directory: async-await

      - run: bun publish
        working-directory: async-await
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          NPM_CONFIG_TOKEN: ${{ secrets.npm_token }}
